eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: api-gateway
zuul:
  routes:
    api-a:
      path: /apiv1/**
      serviceId: service-hi
